/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
function e(e,r,n,t){return new(n||(n=Promise))((function(a,o){function i(e){try{l(t.next(e))}catch(e){o(e)}}function u(e){try{l(t.throw(e))}catch(e){o(e)}}function l(e){var r;e.done?a(e.value):(r=e.value,r instanceof n?r:new n((function(e){e(r)}))).then(i,u)}l((t=t.apply(e,r||[])).next())}))}function r(e,r){var n,t,a,o,i={label:0,sent:function(){if(1&a[0])throw a[1];return a[1]},trys:[],ops:[]};return o={next:u(0),throw:u(1),return:u(2)},"function"==typeof Symbol&&(o[Symbol.iterator]=function(){return this}),o;function u(o){return function(u){return function(o){if(n)throw new TypeError("Generator is already executing.");for(;i;)try{if(n=1,t&&(a=2&o[0]?t.return:o[0]?t.throw||((a=t.return)&&a.call(t),0):t.next)&&!(a=a.call(t,o[1])).done)return a;switch(t=0,a&&(o=[2&o[0],a.value]),o[0]){case 0:case 1:a=o;break;case 4:return i.label++,{value:o[1],done:!1};case 5:i.label++,t=o[1],o=[0];continue;case 7:o=i.ops.pop(),i.trys.pop();continue;default:if(!(a=i.trys,(a=a.length>0&&a[a.length-1])||6!==o[0]&&2!==o[0])){i=0;continue}if(3===o[0]&&(!a||o[1]>a[0]&&o[1]<a[3])){i.label=o[1];break}if(6===o[0]&&i.label<a[1]){i.label=a[1],a=o;break}if(a&&i.label<a[2]){i.label=a[2],i.ops.push(o);break}a[2]&&i.ops.pop(),i.trys.pop();continue}o=r.call(e,i)}catch(e){o=[6,e],t=0}finally{n=a=0}if(5&o[0])throw o[1];return{value:o[0]?o[1]:void 0,done:!0}}([o,u])}}}var n,t=function(e){n=e},a=function(){return n};function o(e){return(new DOMParser).parseFromString(e,"text/html").documentElement.textContent}function i(t){var a=t.language,o=t.aliases,i=void 0===o?[]:o,u=t.defineLanguage;return e(this,void 0,void 0,(function(){return r(this,(function(e){return n&&a&&(u&&n.registerLanguage(a,u),n.registerAliases(i,{languageName:a})),[2]}))}))}var u=function(e,r){var t=void 0===r?{}:r,a=t.getMatch,o=void 0!==a&&a,i=t.error,u=void 0!==i&&i;if(n){if(void 0===typeof e)return n.listLanguages();var l=void 0,c=void 0;"string"==typeof e&&(e=e.split(",").filter((function(e){return e})).map((function(e){return e.trim()})));for(var f=0,s=e;f<s.length;f++){var g=s[f];if(l=g,c=n.getLanguage(g))break}if(u&&!c)throw Error("Unknown language(s) "+e.join(", "));return o&&c?l:c}},l=function(e,r,t){void 0===e&&(e=""),void 0===r&&(r=""),void 0===t&&(t=!0);var a=u(r,{error:t,getMatch:!0});if(console.log({language:a,languageAndOrAliases:r}),!a)return e;for(var o="",i=0,l=e.split("\n");i<l.length;i++){var c=l[i];o+=n.highlight(c,{language:a}).value+"<br>"}return o},c=function(e,r){for(var n=/<pre><code( class=['"]language-(?<lang>[a-z,]+)['"])?>(?<code>(?:(?!<\/code><\/pre>).[\n\t]*)+)<\/code><\/pre>/,t="",a="";;){var i=e.match(n);if(!i)break;var u=o(i.groups.code),c=i.groups.lang;if(t===u&&a===c)break;t=u,a=c;var f=l(u,c,r);e=c?e.replace(i[0],"<pre><code class='hljs "+c+"'>"+f+"</code></pre>"):e.replace(i[0],"<pre><code class='hljs'>"+f+"</code></pre>")}return e};export{c as Highlight,a as getHljs,u as getLang,l as highlightCode,t as setHljs,i as setLang};
